### PR TITLE
Validate multi-ticket PR title

### PR DESCRIPTION
**Pull request by biancapower**
**Jira**: https://macuject.atlassian.net/browse/PF-171

## Description

Update regex to handle both multi ticket and single ticket PR titles.

## Impact Assessment

As part of our ongoing commitment to maintaining compliance with SOC 2 and HIPAA regulations, each proposed change should have an impact assessment undertaken. Our [impact assessment] documentation contains a summary and complete details.

- **High**: Potential for significant harm to sensitive data or user access and material adverse impact on Macuject's operations or reputation.
- **Medium**: Potential for moderate harm to sensitive data or user access and adverse impact on Macuject's operations or reputation.
- **Low**: Unlikely to significantly harm sensitive data or user access, and no expected material adverse impact on Macujects's operations or reputation.
- **None**: Changes that are not relevant to the impact assessment process. Changes will not be used in production by Macuject customers and are related to internal tooling, documentation, or other non-production systems.

**Impact Assessment for this PR**: Low

## Checklist

I've considered all of the following and added to the proposed changes where relevant to this PR:

- [x] Comments for complex or unclear sections
- [x] Logging to assist production operation
- [x] Documentation and diagram updates (e.g. Confluence pages, local markdown docs, architecture diagrams)

I've considered all of the following and added details to the PR description where relevant:

- [x] Breaking changes
- [x] UAT guidance
- [x] Data-related changes
- [x] Job(s) have been described and a [PR opened][job process] for the platform team to review
- [x] Security changes. This also requires the Macuject Information Security Officer to be added to this PR as an additional reviewer.

[job process]: https://macuject.atlassian.net/wiki/spaces/TT/pages/1705082972/Automated+Jobs
[impact assessment]: https://docs.google.com/document/d/1MSPJaPb9LaLvJEH6PIaRULBcz7IaODjRuE6_9hlhHMI

### CODE REVIEW

**Review by bradleybeddoes — CHANGES_REQUESTED** [review]
Propose a more rigid regex per https://regexr.com/7knbj

**Comment by biancapower** [comment]
> https://regexr.com/7knbj

I see what you're going for, but we need to handle EITHER a single issue key OR multiple, and when it's multiple it MUST be surrounded by `[]`, otherwise a later script will fail.

How about: https://regexr.com/7knbs

**Comment by bradleybeddoes** [comment]
Updated proposed Regex in that case: https://regexr.com/7knbj

``` regex
^\[?([A-Z]{2,4}-\d{2,5}(,\s)?)+\]?:|^([A-Z]{2,4}-\d{2,5}):
```

**Comment by biancapower** [comment]
> Updated proposed Regex in that case: https://regexr.com/7knbj
> 
> ```regexp
> ^\[?([A-Z]{2,4}-\d{2,5}(,\s)?)+\]?:|^([A-Z]{2,4}-\d{2,5}):
> ```

👍 updated

**Review by bradleybeddoes — APPROVED** [review]

**Pull request merged**
