### PR TITLE
PF-260: Make screenshots and other images uploaded to PR description accessible via Jira ticket

### PR DESCRIPTION
**Pull request by biancapower**
**Jira**: https://macuject.atlassian.net/browse/PF-260

## Description

- Parses any links for images uploaded to the Jira ticket, downloads the image, then uploads (attaches) it to the Jira ticket.
- Refers to the attachment by name in the comment text, as well as providing a link to download the attachment.
  - Noting for future selves that this was the agreed upon compromise, as I was unable to find a solution for either embedding the attachment into the comment itself, or providing a link to an attachment that would open in browser (a "thumbnail" link will do this, but the resolution is too low to be useful for screenshots, which is our primary use case).

@bradleybeddoes realising as I write the details below that the new PAK is similar to our exisiting `READ_ONLY_ORG_TEAM_MEMBERS` token (see https://macuject.atlassian.net/wiki/spaces/TT/pages/1730805838/GitHub#Automation) but with an additional permission. If you would prefer these to be combined to use the one token instead of separate, happy to do that - just let me know what name you would like to give it and I'll update the code accordingly.

@bradleybeddoes as discussed, before this PR is merged could you please add an additional `secret` to the Macuject GitHub Org. Details as follows:
- Name of secret: `CLASSIC_WORKFLOW_TOKEN`
- Where to add it: This is tricky for me to test, as I can try it with org secrets on my free account, but I believe it needs to be added to the Org secrets. If we find this doesn't work, we'll need to debug.
- What to create: A "classic" personal access token. 
  - Go to https://github.com/settings/tokens -> Generate new token -> Generate new token (classic). 
  - Select "workflow", which will also tick the "repo" boxes as they are necessary for the workflow. See screenshot below.

Screenshot 2024-05-31 at 9 41 21 am

### Before

Screenshot 2024-05-31 at 9 53 34 am

### After

Screenshot 2024-05-31 at 9 55 49 am

## Impact Assessment

As part of our ongoing commitment to maintaining compliance with SOC 2 and HIPAA regulations, each proposed change should have an impact assessment undertaken. Our [impact assessment] documentation contains a summary and complete details.

- **High**: Potential for significant harm to sensitive data or user access and material adverse impact on Macuject's operations or reputation.
- **Medium**: Potential for moderate harm to sensitive data or user access and adverse impact on Macuject's operations or reputation.
- **Low**: Unlikely to significantly harm sensitive data or user access, and no expected material adverse impact on Macujects's operations or reputation.
- **None**: Changes that are not relevant to the impact assessment process. Changes will not be used in production by Macuject customers and are related to internal tooling, documentation, or other non-production systems.

**Impact Assessment for this PR**: None

## Checklist

I've considered all of the following and added to the proposed changes where relevant to this PR:

- [x] Comments for complex or unclear sections
- [x] Logging to assist production operation
- [x] Documentation and diagram updates (e.g. Confluence pages, local markdown docs, architecture diagrams)

I've considered all of the following and added details to the PR description where relevant:

- [x] Breaking changes
- [x] UAT guidance
- [x] Data-related changes
- [x] Job(s) have been described and a [PR opened][job process] for the platform team to review
- [x] Security changes. This also requires the Macuject Information Security Officer to be added to this PR as an additional reviewer.

[job process]: https://macuject.atlassian.net/wiki/spaces/TT/pages/1705082972/Automated+Jobs
[impact assessment]: https://docs.google.com/document/d/1MSPJaPb9LaLvJEH6PIaRULBcz7IaODjRuE6_9hlhHMI

### CODE REVIEW

**Comment by biancapower** [comment]
I will update the relevant Confluence doc once we have confirmed the new variable name and seen this working.

**Comment by bradleybeddoes** [comment]
Single token sounds good @biancapower - How about `ORG_TEAM_MEMBERS` ?

**Comment by bradleybeddoes** [comment]
Screenshot 2024-06-03 at 12 53 36 PM

Have added a new key and secret.

Both have the workflow permission now if that helps testing. Once sorted I will delete the earlier named key/secret.

**Comment by biancapower** [comment]
Thanks @bradleybeddoes , variable name updated to the new key.

**Review by bradleybeddoes — APPROVED** [review]

**Pull request merged**
